[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
    "pip install -r commet-remote-data-server/requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "cd commet-remote-data-server && python server.py"
